"""Render generated infrastructure snippets back into valid HCL.

The rules engine attaches a ``generated_code`` structure to recommendations. This
module serializes that structure into human-readable Terraform source that users
can drop into their repository.

Validation pipeline:
  1. Structural validation (block types, resource names, reserved words)
  2. HCL syntax validation using the project's HCL2 parser
  3. Reference validation (generated code references only existing resources)
"""

from __future__ import annotations

from typing import Any


def _is_tf_expression(value: str) -> bool:
    """Return True if the string is a Terraform expression, not a literal string.

    Terraform expressions include:
      - resource references: aws_s3_bucket.name.id
      - variable references: var.name
      - local references: local.name
      - module references: module.name.output
      - data sources: data.aws_ami.latest.id
      - built-ins: count.index, each.key, self.name
      - string interpolation: ${...}
      - function calls: concat(...), lookup(...)
    """
    if not isinstance(value, str):
        return False
    # String interpolation is always an expression
    if "${" in value:
        return True
    # Function calls: name(...)
    if re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*\(", value):
        return True
    # Terraform references: resource_type.name[.attr...]
    # or var.name, local.name, module.name, data.type.name, self.name
    if re.match(
        r"^(var|local|module|data|self|count|each)\.[a-zA-Z_]",
        value,
    ):
        return True
    # aws_/google_/azurerm_ resource references
    if re.match(
        r"^(aws|google|azurerm|digitalocean|hcloud|scaleway|ovh|oci|vultr|linode|cloudflare|kubernetes|openstack)_",
        value,
    ):
        return True
    return False


def _fmt_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        # Terraform expressions are rendered unquoted
        if _is_tf_expression(value):
            return value
        return f'"{value}"'
    if isinstance(value, dict):
        return _fmt_map(value)
    if isinstance(value, list):
        return _fmt_list(value)
    return f'"{value}"'


def _fmt_map(mapping: dict) -> str:
    if not mapping:
        return "{}"
    inner = ",\n    ".join(f"{k} = {_fmt_value(v)}" for k, v in mapping.items())
    return f"{{\n    {inner}\n  }}"


def _fmt_list(items: list) -> str:
    if not items:
        return "[]"
    inner = ",\n    ".join(_fmt_value(i) for i in items)
    return f"[\n    {inner}\n  ]"


def render_resource(block_type: str, name: str, config: dict, indent: int = 0) -> str:
    """Render a single ``resource "type" "name" { ... }`` block."""
    pad = "  " * indent
    lines = [f'{pad}resource "{block_type}" "{name}" {{']
    lines.append(_render_config(config, indent + 1))
    lines.append(f"{pad}}}")
    return "\n".join(lines)


def _render_config(config: dict, indent: int) -> str:
    pad = "  " * indent
    lines: list[str] = []
    for key, value in config.items():
        if isinstance(value, dict) and not _is_interpolation_like(value):
            lines.append(f"{pad}{key} {{")
            lines.append(_render_config(value, indent + 1))
            lines.append(f"{pad}}}")
        elif isinstance(value, list) and value and all(isinstance(i, dict) for i in value):
            for _idx, item in enumerate(value):
                lines.append(f"{pad}{key} {{")
                lines.append(_render_config(item, indent + 1))
                lines.append(f"{pad}}}")
        else:
            lines.append(f"{pad}{key} = {_fmt_value(value)}")
    return "\n".join(lines)


def _is_interpolation_like(value: dict) -> bool:
    return "$" in str(value.get("value", "")) or False


def render_generated_code(generated: dict | None) -> str:
    """Render the full generated_code payload into an HCL artifact string."""
    if not generated:
        return ""
    sections: list[str] = []
    sections.append("# Generated by CloudPilot AI — apply after review\n")
    for block_type, payload in generated.items():
        if not isinstance(payload, dict) or "name" not in payload:
            continue
        name = payload["name"]
        config = payload.get("config", {})
        sections.append(render_resource(block_type, name, config))
        sections.append("")
    return "\n".join(sections)


def render_optimized_project(blocks: list[dict]) -> str:
    """Render a full optimized project artifact from multiple resource blocks."""
    parts = ["# CloudPilot AI — optimized Terraform\n"]
    for block in blocks:
        parts.append(render_resource(block["resource_type"], block["name"], block["config"]))
        parts.append("")
    return "\n".join(parts)


# --- Structural validation for generated Terraform code ---

# Valid top-level Terraform block types
_VALID_BLOCK_TYPES = {
    "resource", "data", "variable", "output", "locals",
    "module", "provider", "terraform", "moved", "import",
}

# Known AWS provider resource types (subset — covers the rules engine output)
_KNOWN_AWS_RESOURCE_TYPES = {
    "aws_instance", "aws_launch_template", "aws_autoscaling_group",
    "aws_ebs_volume", "aws_s3_bucket", "aws_s3_bucket_server_side_encryption_configuration",
    "aws_s3_bucket_versioning", "aws_nat_gateway", "aws_eip",
    "aws_db_instance", "aws_elasticache_cluster", "aws_elasticache_replication_group",
    "aws_cloudwatch_log_group", "aws_cloudwatch_metric_alarm",
    "aws_sns_topic", "aws_sqs_queue", "aws_lambda_function",
    "aws_iam_role", "aws_iam_policy", "aws_security_group",
    "aws_vpc", "aws_subnet", "aws_route_table",
    "aws_lb", "aws_lb_target_group", "aws_lb_listener",
    "aws_ecs_service", "aws_ecs_task_definition", "aws_ecs_cluster",
    "aws_ecs_cluster_capacity_providers",
}

import re


def detect_provider_version(config_files: dict[str, str] | None = None) -> str | None:
    """Detect the AWS provider version from Terraform configuration.

    Checks:
    1. required_providers block for hashicorp/aws version constraint
    2. terraform.lock.hcl for exact resolved version
    3. provider "aws" block for any version hint

    Returns version string like "~> 5.0" or "5.31.0" or None if not detectable.
    """
    if not config_files:
        return None

    for path, content in config_files.items():
        if not content:
            continue

        # Check terraform.lock.hcl for exact version
        if path.endswith("terraform.lock.hcl"):
            match = re.search(r'version\s*=\s*"(\d+\.\d+\.\d+)"', content)
            if match:
                return match.group(1)

        # Check required_providers block
        match = re.search(
            r'aws\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
            content,
            re.DOTALL,
        )
        if match:
            return match.group(1)

    return None


# Fields that should never appear as HCL attributes (Terraform reserved words)
_RESERVED_HCL_WORDS = {
    "resource", "data", "variable", "output", "locals",
    "module", "provider", "terraform", "moved", "import",
    "count", "for_each", "depends_on", "lifecycle",
}


def _parse_hcl_syntax(hcl_text: str) -> tuple[bool, list[str]]:
    """Attempt to parse the generated HCL text using the project's HCL2 parser.

    Returns (valid, errors).
    """
    try:
        from app.services.terraform.hcl import parse_hcl

        parse_hcl(hcl_text)
        return True, []
    except Exception as exc:
        return False, [f"HCL syntax error: {exc}"]


def validate_generated_block(block_type: str, name: str, config: dict) -> list[str]:
    """Validate a single generated resource block.

    Returns a list of validation error strings. Empty list = valid.
    """
    errors: list[str] = []

    # 1. Block type must be a known cloud resource type
    if not block_type.startswith(("aws_", "google_", "azurerm_")):
        errors.append(f"Unknown resource type '{block_type}' — not a recognized cloud provider prefix")
    elif block_type not in _KNOWN_AWS_RESOURCE_TYPES:
        errors.append(
            f"Resource type '{block_type}' has a valid provider prefix but is not in the "
            f"known-types list — verify it exists in your provider version"
        )

    # 2. Resource name must be a valid Terraform identifier
    if not name or not name[0].isalpha() and name[0] != "_":
        errors.append(f"Resource name '{name}' must start with a letter or underscore")
    if not all(c.isalnum() or c in ("_", "-") for c in name):
        errors.append(f"Resource name '{name}' contains invalid characters (use only a-z, 0-9, _, -)")

    # 3. Config keys must not be Terraform reserved words
    for key in config:
        if key in _RESERVED_HCL_WORDS:
            errors.append(f"Attribute '{key}' is a Terraform reserved word — not valid in a resource block")

    # 4. Check for empty config blocks
    if not config:
        errors.append(f"Resource '{block_type}.{name}' has an empty configuration block")

    # 5. Nested interpolation values should use proper HCL syntax
    def _check_interpolations(obj: Any, path: str = "") -> None:
        if isinstance(obj, dict):
            for k, v in obj.items():
                _check_interpolations(v, f"{path}.{k}")
        elif isinstance(obj, str):
            # Check for incomplete interpolation: ${...} without closing }
            if "${" in obj:
                opens = obj.count("${")
                closes = obj.count("}")
                if opens > closes:
                    errors.append(f"Unclosed interpolation at {path or 'root'}: '{obj[:80]}...'")

    _check_interpolations(config)

    return errors


def validate_generated_code(blocks: list[dict]) -> dict:
    """Validate all generated code blocks.

    Returns a dict with:
      - valid: bool
      - errors: list of {resource_type, name, errors} dicts
      - warnings: list of non-blocking warning strings
      - total_blocks: int
      - valid_blocks: int
      - hcl_syntax_valid: bool (whether the rendered HCL parses successfully)
    """
    all_errors: list[dict] = []
    warnings: list[str] = []
    valid_count = 0

    for block in blocks:
        block_type = block.get("resource_type", "")
        name = block.get("name", "")
        config = block.get("config", {})
        errors = validate_generated_block(block_type, name, config)
        if errors:
            all_errors.append({
                "resource_type": block_type,
                "name": name,
                "errors": errors,
            })
        else:
            valid_count += 1

    # HCL syntax validation: render all blocks and try to parse
    hcl_syntax_valid = True
    if blocks:
        rendered = render_optimized_project(blocks)
        syntax_ok, syntax_errors = _parse_hcl_syntax(rendered)
        hcl_syntax_valid = syntax_ok
        if not syntax_ok:
            warnings.extend(syntax_errors)

    is_valid = len(all_errors) == 0 and hcl_syntax_valid

    # Determine validation status label
    if is_valid:
        validation_status = "copy_paste_ready"
        validation_label = "Copy-paste ready"
    else:
        validation_status = "requires_validation"
        validation_label = "Generated suggestion — requires validation"

    return {
        "valid": is_valid,
        "validation_status": validation_status,
        "validation_label": validation_label,
        "errors": all_errors,
        "warnings": warnings,
        "total_blocks": len(blocks),
        "valid_blocks": valid_count,
        "hcl_syntax_valid": hcl_syntax_valid,
    }
